### ISSUE TITLE
Add CouchDB Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#416]
# Goal
An efficient CouchDB template for creating DBs with strong data consistency and built-in conflict resolution, ideal for applications that prioritize data integrity

## Payout
$200

## Expectation
Create a CouchDB template with the necessary configurations. Provide comprehensive documentation to guide users through the setup and usage of the template.

**Comment by Aravindha1234u** [comment]
Will work on this.

**Comment by Aravindha1234u** [comment]
Completed and Tested 
Template: https://railway.app/template/eRC98l?referralCode=HT4TtK
Github Repo: https://github.com/Aravindha1234u/couchdb-railway

**Comment by Aravindha1234u** [comment]
@ndneighbor I have published the template

**Comment by melissa-hale** [comment]
Hey @Aravindha1234u !  This is so great, thank you for putting in so much time to put it together and provide solid documentation.  I love the extra touch of including a python script to show how you can interact with your DB too.  Just a couple things to note - 

1.  This was for Couchbase not CouchDB!  Definitely willing to accept it though, don't worry. Looking at the images, CouchDB has almost double the pulls compared to Couchbase, so this is a great addition to the marketplace.  I'm curious though if that was a miss, or you made the decision to do CouchDB instead of Couchbase, and if so, could you enlighten me?
2. Instead of prompting to input a CouchDB username as part of the template flow, we should go ahead and define a default.  My initial thought when I saw the prompt was that I would have to sign up for something and get a user name.  I think defining it, maybe like `admin` or something simple, then calling that out in the docs would be a smoother experience. Open to hearing any arguments of course, just lmk
3. The last line in your python script `server.disconnect()` throws an error bc the function doesn't exist on the object.  Might not need that?  or i could have installed the wrong package (`pip install couchdb`).

All that said!  Once you address the 2 things above, please push your code into this repo: https://github.com/railwayapp-templates/couchdb.  Then update the template config to point to that repo.  When you're done, send me an email at melissa@railway.app.  I'll make a final pass then start the payout!

**Comment by Aravindha1234u** [comment]
1. I really missed it was for Couchbase. I thought was requirement was for CouchDB. 
2. Yes I have updated the template with the user as an optional value.
3. Also I have removed the one line for server disconnect from the example Python program. 

@melissa-hale

**Comment by melissa-hale** [comment]
Great, thanks @Aravindha1234u !  Please update the template config to point to the new repo, also please add a line in the docs to clarify the user can find their credentials to the CouchDB WebUI in the env vars for the service.

After, send me an email at melissa@railway.app, and we'll work out details for the payout.  We prefer to do it via Github sponsorship but can also accommodate BuyMeACoffee.

**Comment by Aravindha1234u** [comment]
Mail Sent! @melissa-hale

**Comment by melissa-hale** [comment]
Thanks @Aravindha1234u ! I got your email and I see that you have updated the template configuration to go to the appropriate repo.  The final pending item is updating the documentation so users know where to find the credentials to access the CouchDB Web UI. Please add a note somewhere in the docs that point the user to the Variables in Railway to get that info.

**Comment by Aravindha1234u** [comment]
@melissa-hale 

![image](https://github.com/railwayapp/templates/assets/52521300/7690407b-f045-4f31-8262-b0f661187751)
I have mentioned that already in README.md let me know if the sentence need to be better written.

**Comment by melissa-hale** [comment]
That looks great, can you please add that line to the template overview so it shows up on the template page too?

Moving this one into Payout Pending to signal this one is done.  I should be getting to the rest of the submissions today, too, just FYI.  Thanks again @Aravindha1234u !

**Comment by Aravindha1234u** [comment]
Okk, I have updated the template info as well you can take a look if you want.
