### ISSUE TITLE
Add MariaDB Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#417]
# Goal
A reliable MariaDB template to quickly set up and configure a MySQL-based database.

## Payout
$200

## Expectation
Develop a MariaDB template that provides seamless linking to a GitHub repository or a Docker image. Include scripts for database initialization and user management. Clear documentation is essential to help users leverage the template effectively.

**Comment by Aravindha1234u** [comment]
Working on this.

**Comment by Aravindha1234u** [comment]
Github Repo: https://github.com/Aravindha1234u/mariadb-railway
Template: https://railway.app/template/BrjaHe?referralCode=HT4TtK

Tested and working as excepted. 
@ndneighbor

**Comment by Aravindha1234u** [comment]
@ndneighbor I have published the template

**Comment by melissa-hale** [comment]
This is deploying nicely however the Adminer part was a little confusing to figure out.  
- that I had to update the server to "database" since it defaulted to db (maybe just update your screenshot here? https://raw.githubusercontent.com/Aravindha1234u/mariadb-railway/main/img/login.png)
- logging in with the user that was created via the env vars, I didn't have any privileges so I had to login with `root` to really do anything.
My only asks with this template are to make those things more clear, also to fix the image reference on the template page for the login screenshot 
<img width="740" alt="image" src="https://github.com/railwayapp/templates/assets/26257950/4904131e-8590-431a-a80f-8ac9e675a5dc">

Thanks @Aravindha1234u !

**Comment by melissa-hale** [comment]
As with the others, once you knock out those things, please push your code to the following template, update you template config and send me an ack :)

https://github.com/railwayapp-templates/mariaDB

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale 

1. Adminer is just GUI to manage any SQL database I just included in this template because Railway doesn't suppose MariaDB management natively so I thought it would be helpful for people to manage with that. 
2. That Login page server value is `db` which is set by default in Adminer. I don't have control over it to update it. I can update the screenshot if you want to replace it. but I have added this line in README.md to help people connect to DB
![image](https://github.com/railwayapp/templates/assets/52521300/9fd3ebe5-e329-4666-a393-9ea604224a47)
3. I don't understand what `root` user you are talking about. if you just use the credentials that you set in the environmental variable you should log in to view the data
4. I have fixed the template info for the login image

**Comment by Aravindha1234u** [comment]
@melissa-hale Pushed the files to new repo and updated the railway template.

**Comment by melissa-hale** [comment]
Hi @Aravindha1234u! Thanks for pushing them to the new repo and updating the template.  The docs make it more clear you need to change the default server.  Yes, I meant you could update the screenshot, but the extra line is fine.  We're good on this one.
