### ISSUE TITLE
Add HiveMQ Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#422]
# Goal
A powerful HiveMQ template to develop high-performance and low-latency message queue solutions.

## Payout
$300

## Expectation
Develop a HiveMQ template showcasing MQTT protocol support and message persistence. Consider incorporating clustering and high-availability configurations. Provide clear documentation to help users effectively deploy and utilize the template.

**Comment by Aravindha1234u** [comment]
Will work on this.

**Comment by Aravindha1234u** [comment]
Template: https://railway.app/template/ELAarG?referralCode=HT4TtK
Github Repo: https://github.com/Aravindha1234u/hivemq-railway
Completed and test it 

@ndneighbor

**Comment by Aravindha1234u** [comment]
I have just updated the template. Since HiveMQ has community and enterprise editions I made the template generic to expose websocket as well as the control center. So any user can use this template to deploy it. But for community center we will not have control center and it will throw 502 error is it ok ?

**Comment by melissa-hale** [comment]
@Aravindha1234u this one is great too and just works.  What I really like about this submission is that you included the `examply.py` file to show how you can implicitly create and subscribe to a topic, and publish a message to that topic.

What I would love to see changed is rewriting your documentation so that it is focused more around what the template _can_ do, and how to get the most out of what you've put together, e.g.
- Highlight how `example.py` not only serves as a means to test, but also as an example of how to actually use the queue
- Go into detail about how they can configure things for clustering and high-availability configurations (as mentioned in the prompt for this submission).  Would this be done via the config.xml?  Where in the docs is this mentioned?
Then, reduce the information about the HiveMQ Control Center since that is not what this template is providing.  I do like that you mention how easy it is to update the service so that it uses the Enterprise Edition.

As an aside, if you included something like the `example.py` in your NSQ template, that would be perfect for answering some of the questions I dropped in that issue for you (https://github.com/railwayapp/templates/issues/421)

**Comment by melissa-hale** [comment]
Once you knock out the adjustment to the docs, here is your repo to push your code into: https://github.com/railwayapp-templates/hiveMQ

I'll look for your ack, and give it one more review.  But I've added this to the payout queue for you too! :)

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale I have updated the documentation and pushed the latest files to the new repository. Also, pointed the railway template new repo.
