### ISSUE TITLE
Add TypeBot Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#427]
# Goal
TypeBot is a self-hosted template designed to create conversation interfaces.

## Payout
$150

## Expectation
Create the TypeBot template. Detailed documentation will guide users in leveraging TypeBot's capabilities for their data automation needs.

**Comment by Aravindha1234u** [comment]
Working on this.

**Comment by Aravindha1234u** [comment]
Github Repo: https://github.com/Aravindha1234u/typebot-railway
Template: https://railway.app/template/dUZFyU?referralCode=HT4TtK

**Comment by Aravindha1234u** [comment]
@ndneighbor I have updated the Template and it works as excepted.

**Comment by FarazPatankar** [comment]
@Aravindha1234u make sure you publish the template on Railway.

**Comment by Aravindha1234u** [comment]
I thought there will an approval process. ok I will go ahead and publish it

**Comment by Aravindha1234u** [comment]
https://railway.app/template/dUZFyU

**Comment by melissa-hale** [comment]
Hi @Aravindha1234u , thank you for your work on this one!  However, another submission will be accepted for TypeBot.  I wanted to provide some feedback though - 
- Using images whenever possible, instead of repo's with Dockerfiles, is preferred
- Usage of reference variables (e.g. `${{Builder.RAILWAY_PUBLIC_DOMAIN}}`) instead of template variables is also preferred

Thanks again for this one and the rest of your submissions.  I know you are working on one more so I'll be on the lookout

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale 

1. I haven't used Repo's Dockerfile if you check I have used the latest image version of Typebot official docker only. Since it has two services I had to put them in different folders.
![image](https://github.com/railwayapp/templates/assets/52521300/0c68cd86-12ad-44fa-b71e-50ed753ecd88)
I had to update `entrypoint.sh` because the latest version contained various bugs which were raised in Railway discord as well as Github Issues in my repository. it was throwing an `Internal Error Server` So I had to debug and fix that since multiple users had started using my template.
![image](https://github.com/railwayapp/templates/assets/52521300/e1a9203f-8d0b-46c3-978e-29f1530afaab)
Is Brody's template accepted for this submission? let me know if that template will be used, I can remove mine but I am not sure if this will affect the active users using my template from Railway's Template marketplace.

3. Secondly, the public_url template service variable is getting assigned after the service starts which makes NEXT_JS fail and stop working so I had to override the variable that's why I have used RAILWAY_PUBLIC_DOMAIN variable which I found from the env variables.

**Comment by melissa-hale** [comment]
Hi @Aravindha1234u !  Completely understand, and I really appreciate you raising your points.  I didn't mean to imply there was anything inherently wrong with your work.  The template is adding huge value to our marketplace, clearly!  I think the best course forward here is to credit you for this bounty as well.  Both of the TypeBot templates are great, and honestly, I love that they show different ways of deploying the same self-hosted system.

I'll get you queued up for payout here as well :)

I think we're pretty good on your submissions so far, so we can keep chatting in Discord!  Thanks again!
