### ISSUE TITLE
Add Openblocks Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#429]
# Goal
OpenBlocks is a self-hosted template, an open-source alternative to Retool, providing a flexible app-building platform.

## Payout
$150

## Expectation
Contribute the OpenBlocks template with a customizable app-building environment. Users should be able to create applications with ease using the template. Comprehensive documentation is essential to guide users through the setup and usage of the template, ensuring a smooth experience.

**Comment by Aravindha1234u** [comment]
I am working on this. 

Here is this repo: https://github.com/Aravindha1234u/openblock-railway
Template Link: https://railway.app/template/z-IiRE?referralCode=HT4TtK

**Comment by Aravindha1234u** [comment]
@ndneighbor I have completed my template and tested it working as excepted.

**Comment by Aravindha1234u** [comment]
@ndneighbor I have published the template.

**Comment by ndneighbor** [comment]
Oh this is killer! Reviewing.

**Comment by melissa-hale** [comment]
Thanks for another great submission @Aravindha1234u .  Can you adjust two things in the template config/overview?

1. your template name is Openblock, can you please update to Openblocks
2. when deploying from the template, there seems to be an issue where the API and node services don't deploy automatically.  We have a ticket logged internally to investigate this, but in the meantime, can you please add a section like "Known Issues" to the overview that acknowledges this and the solution is to pull down the repo, use the railway CLI to link to the project, and run `railway up` for both of the services that don't deploy? screenshot to help with clarity - 
<img width="492" alt="image" src="https://github.com/railwayapp/templates/assets/26257950/3240e956-9137-41fb-a5dd-26cccc6ea18f">

Lastly, push your code to this repo and update the template config to point to it: https://github.com/railwayapp-templates/openblocks

I am tracking your submission payouts together, so I'll be adding this one to the list.

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale 

1. I have updated the name in the Railway template.
2. I am not sure what you are mentioning service doesn't deploy automatically. I just tried deploying the template all 3 services and 2 databases deployed at the same time and I didn't have this issue. It may take some time to deploy and you may need to redeploy any one of the services. I guess that is either because it's a little bit huge or it could be railway traffic or serverside load.
![image](https://github.com/railwayapp/templates/assets/52521300/009347d9-b081-4732-b7cf-237ff0736b49)
![image](https://github.com/railwayapp/templates/assets/52521300/0d81775a-ce1b-4658-8d79-174f648db587)

But I have added the `Known Issues` in README.

**Comment by Aravindha1234u** [comment]
@melissa-hale I have made the changes pushed them to the new repo and updated the template to point to that
