### ISSUE TITLE
Add Chroma Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#434]
# Goal
Chroma is an AI/ML Vector Database template designed for efficient storage and retrieval of high-dimensional vector data.

## Payout
$300

## Expectation
Create the Chroma template with seamless integration for AI/ML vector data storage. It should support indexing and querying of vector data efficiently.

**Comment by honzasterba** [comment]
done https://railway.app/template/tifygm

**Comment by ndneighbor** [comment]
Jan, you are a genius. Going to review this now with the team. Thank you soooo much @honzasterba.

**Comment by Xevion** [comment]
@honzasterba Someone posted in the Railway discord that the _Getting Started_ link is 404'ing, it has a typo.

![image](https://github.com/railwayapp/templates/assets/44609630/6f997ccb-709e-4cb3-b133-40614cf4c2d5)

At the start of the URL, a `[` is present.

**Comment by honzasterba** [comment]
fixed

**Comment by honzasterba** [comment]
how's the review coming along?

**Comment by melissa-hale** [comment]
@honzasterba thanks for your patience and thanks for a great submission.  I see it's already being used quite a bit!  Since you based your template on a Docker image, all that's left is getting the payout started.  Could you please send me an email at melissa@railway.app and we'll coordinate from there :)
