### ISSUE TITLE
Go Mux Starter

### ISSUE THREAD

**Issue by himeshp** [railwayapp/templates#448]
### Contact Details

himeshp on discord

### Template URL

https://railway.app/template/Fx4u79?referralCode=VxaV3q

### What does this template deploy?

This template deploys a Go Mux starter, as requested in https://github.com/railwayapp/templates/issues/414

**Comment by ndneighbor** [comment]
Reviewing!

**Comment by melissa-hale** [comment]
Hi @himeshp !  First, I wanted to thank you for your submission and for the time you spent putting it together.  However, we will be accepting another submission for this bounty.  I wanted to provide some feedback in case its helpful:

When deploying from your template, the app fails to respond :( A cursory glance at the code tells me it's because you aren't using the PORT environment variable.  Checkout this article in docs for more details: https://docs.railway.app/troubleshoot/fixing-common-errors#application-error-this-application-failed-to-respond

One other minor thing, in case you want to submit for other bounties - when viewing your template, there is no documentation.  When you publish your template, you are given the opportunity to provide an Overview/Documentation that will show up on the page for the template in the marketplace.  That is one thing I am checking when reviewing these!  I do see that you have a nice README in your repo, that's great!  Just remember there is that additional place for describing your template and highlighting the features right from the marketplace. --> https://docs.railway.app/reference/templates#publishing-a-template

Thanks again!
