### ISSUE TITLE
Add Vue 3 Starter

### ISSUE THREAD

**Issue by brody192** [railwayapp/templates#455]
### Contact Details

https://discord.gg/railway

### Template URL

https://railway.app/template/Qh0OAU

### What does this template deploy?

A static Vue 3 demo app, served with [Caddy](https://caddyserver.com/) used to show off a best practices deployment. As requested in the Notion doc

### Demo project

https://railway.app/project/9c3f6dc2-6129-4ace-9005-6eede16b7c6e

**Comment by melissa-hale** [comment]
So good @brody192 !  Thanks for another excellent submission.  We'll get you paid on this too, but I just have one weird thing to raise, that has nothing to do with your code, but how the repo is being cloned into my account.. it's cloning it as `-Vue-3` which is annoying because when I try to open it in VSCode from my terminal running `code -Vue-3`, it errors with `Warning: 'V' is not in the list of known options` because it thinks i'm trying to use a switch.

<img width="316" alt="image" src="https://github.com/railwayapp/templates/assets/26257950/b45ebe42-cdb9-44c2-b107-64d84be00c16">

any idea why it's being created with that funky repo name?  does the same thing happen to you?

**Comment by brody192** [comment]
![image](https://github.com/railwayapp/templates/assets/10548119/f33e0431-c5e3-46a7-b696-2130fcfe3cd0)
Github is escaping the whitespace, good catch! all fixed

**Comment by melissa-hale** [comment]
OOooO good to know that's where it was coming from, thank you for fixing it!

Here is your repo, if you don't mind pushing your code over: https://github.com/railwayapp-templates/vue-starter

**Comment by brody192** [comment]
pushed and updated!
